languageCode = 'en-us'
title = 'Cosmos'
theme = "cosmos"
MetaDataFormat = "yaml"

[menu]
  [[menu.main]]
    identifier = "About"
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = -110

[markup]
  [markup.highlight]
    style = 'solarized-dark'
    codeFences = true
    guessSyntax = false
    lineNoStart =1
    lineNos = true
    lineNumbersInTable = true

[module]
[[module.mounts]]
  source = 'assets'
  target = 'assets'

[params]
  author = "Houmin"
  description = "Demo for Hugo Cosmos"
  since = "2019"
  dateFormat = "January 2, 2006"

  ShowPostNavLinks = true
  ShowBreadCrumbs = true

  linkToMarkDown = false    # if you config contentCopyright and hugo output .md files
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  enableGitInfo = true

  [[params.assets]]
    favicon = "/static/favicon/favicon.ico"
    favicon16x16 = "/static/favicon/favicon-16x16.png"
    favicon32x32 = "/static/favicon/favicon-32x32.png"
    apple_touch_icon = "/static/favicon/apple_touch_icon.png"

  [[params.rewards]]
    enableWechatPay = true
    wechatPay = "https://cosmos-1251905798.cos.ap-beijing.myqcloud.com/theme/wechatpay.png"
    enableAliPay = true
    aliPay = "https://cosmos-1251905798.cos.ap-beijing.myqcloud.com/theme/alipay.jpg"

  [params.gitInfo]
    gitRepo = "https://github.com/SimpCosm/hugo-theme-cosmos-demo"
    showCommitMessage = true

  [params.giscuss]
    enable = true
    repo = "SimpCosm/hugo-theme-cosmos-demo"
    repoId = "R_kgDOIJ9C6g"
    category = "Announcements"
    categoryId = "DIC_kwDOIJ9C6s4CS0YL"
